### ISSUE TITLE
GetPredictions takes a ushort value for the fixture parameter when it should be an int

### ISSUE THREAD

**Issue by Krazh** [fabricatorsltd/api-sports#3]
The API uses an integer for fixture Id as there is many more fixtures than the max value of ushort. I haven't checked if ushort is being used in other situations like this.

**Comment by pietrodicaprio** [comment]
`ushort` is from 0 to 65.535\
To be honest I did't see fixtures with higher id but makes sense that could be present one day or another.\
Should I use `uint` instead of `int` anyway? Did you ever see negative fixtures id? (uint is up to 4.294.967.295, should be enough for a long time 😅)

**Comment by pietrodicaprio** [comment]
Looking the code I see that Predictions->GetPredictions() is already asking for an uint, not an ushort. Maybe I misunderstood where did you see it?

**Comment by Krazh** [comment]
Well I'm the idiot then 😄 sorry, 
I think I assumed that it was a ushort and just cast it as that without checking. Odd that I didn't get any warning.

**Comment by pietrodicaprio** [comment]
Don't worry, it happens! Good that is already fine then. I'm sure you'll find something else anyway :)
